cac-prod.yml
=> Update platform regex for build monitor

cac-prod.yml
=> Added probate & INTESTACT to cac-prod.yml

env_vars/prod.yml
There's extra vars to be updated I wasn't aware of during #169. Amending nightly section for platform - second attempt
=> Include spring-boot-template in nightly

playbook.yml
Getting the latest plugin to fix the saucelabs reporting issues
=> Updating the sauce-plugin version

playbook.yml
Sets one executor per agent, with max 40 agents
=> update executor/agent config

playbook.yml
Works around https://issues.jenkins-ci.org/browse/JENKINS-54885
Notes:
*
*
*
=> Upgrade azure vm agents plugin

cac-prod.yml, cac-sandbox.yml
Add div build monitor to sandbox and prod
=> DIV-3510 - add div build monitor

cac-prod.yml
div-ansible
div-case-progression-service
div-feature-toggle-client
div-frontend-boilerplate
=> Remove legacy div projects from build monitor

env_vars/prod.yml, env_vars/sandbox.yml, playbook.yml
We are starting a new project - Access Management (AM)
Added entries to prod, sandbox and playbook in order preview AM project in Jenkins
=> Added AM records to prod.yml, sandbox.yml and playbook.yml

cac-prod.yml
=> Added am build monitors

jobdsl/organisations.groovy
=> Fix PRs and demo not triggering

jobdsl/organisations.groovy
=> Fix credential on test org

jobdsl/organisations.groovy
=> Add PRs to included on test organisation

jobdsl/organisations.groovy
=> Fix org scan

cac-prod.yml, jobdsl/organisations.groovy, playbook.yml
=> Added jenkins-reform-ethos org

cac-prod.yml, cac-sandbox.yml, cac-test.yml
Will remove old code in a separate PR as that needs more testing
=> Convert to configuration as code

cac-prod.yml
https://tools.hmcts.net/jira/browse/RDM-3993
=> Add CDM demo build monitor

jobdsl/organisations.groovy
Need to raise a corresponding pipeline pr to change to call plum
Just added plum for now so it's a non-breaking change. Will need another PR to remove rhubarb once the change to the pipeline test code has been made.
=> Switch from rhubarb to plum for pipeline testing

cac-sandbox.yml
Also adds missing environment variable config for sandbox
=> Use `saat` for prod test stages

cac-prod.yml, jobdsl/organisations.groovy, playbook.yml
Notes:
* Adding Ref Data org as this is a new team to use in Jenkins.
* 
*
=> Adding Ref Data org

cac-prod.yml
=> Add plumb to builds the platform team monitors

jobdsl/organisations.groovy
=> Removing ways for team to bypass master

cac-prod.yml
=> Add REGISTRY_NAME env

jobdsl/organisations.groovy
Added `perftest` environment in the Branches To Include
=> Added perftest environment

jobdsl/organisations.groovy
Added ithc environment in the Branches To Include
=> added ithc environment

cac-prod.yml
=> Update PDF service name

playbook.yml
This allows us to use Sauce labs Eu data center
=> sauce-ondemand plugin update

cac-prod.yml, cac-sandbox.yml, cac-test-local.yml, cac-test.yml, playbook.yml, plugins.txt
=> Plugin updates / manual changes back-porting

cac-prod.yml, cac-sandbox.yml
https://tools.hmcts.net/jira/browse/RPE-1045
Notes:
* Adding Env Vars for AKS cluster name and Resource group.
=> Adding Env Vars for AKS cluster config

cac-sandbox.yml
=> Fixing sandbox values

cac-prod.yml
=> Fixing typo for RG name

playbook.yml
Notes:
* Adding credentials for owasp postgresql db
=> Adding credentials for owasp postgresql db

playbook.yml
=> fixing indentation

cac-test.yml, playbook.yml
Update `test` config to be passive wrt github and not process any repos
Added missing `sauce` api key for the build
=> Modifytest config

jobdsl/organisations.groovy
Add preview to list of branches to display
=> add preview to  list of branches

cac-sandbox.yml
=> RPE-1106 Update environment name for sandbox

cac-prod.yml, cac-sandbox.yml
Resolves [AB#178](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/178)
Notes:
* Idea is to make moving aat and preview to new subscriptions as well simply config change
* Only preview and AAT are added, assuming we won't need Jenkins to deploy to another envs, #Gitops
=> Adding aks subscription names for prod and sandbox jenkins

cac-sandbox.yml
Notes:
*moving to new sandbox cluster
=> moving to new sandbox cluster

plugins.txt
=> azure vm agents updated to last version

cac-prod.yml
=> Add evidence share project to dashboard

cac-prod.yml
Adding keyvault name to retrieve tls certs.
=> Moving over to new AAT subscription

jobdsl/organisations.groovy
=> ethosldata

cac-prod.yml, cac-sandbox.yml
=> Aks infra rg

cac-prod.yml, cac-sandbox.yml
Config was exported from running noe
=> Add azure vm agent config to JCasC

cac-prod.yml, cac-sandbox.yml
=> Update env vars for AKS

cac-sandbox.yml
=> Update agent in sandbox (add nvm)

cac-sandbox.yml
Jenkins doesn't load the profile information, no need to add it to jenkins shell
=> Update image and remove nvm shell source

team-config.yml
Feel it makes sense to have a seperate NS for camunda?
Notes:
*
*
*
=> Adding Camunda NS

CODEOWNERS
Fixes [AB#477](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/477)
=> Add CODEOWNERS to cnp-jenkins-config

jobdsl/organisations.groovy
Fixes [AB#499](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/499)
=> Fix sandbox builds not triggering properly

team-config.yml
Notes:
* Gave best shot by looking at jenkins files , but not all.
=> Adding default slack channel config

team-config.yml
=> Add contact channel along with build notice channels

team-config.yml
Updating slack channel references for reference data.
=> Updating slack channel details for reference data

team-config.yml
Adding core-infra as requested by TimJ
Resolves # Jenkins build fails as the 'core-infra' is missing from team-config.yml
=> Add core-infra

team-config.yml
Changing namespace from immigratiom to ia
=> changing team config from immigration to ia

team-config.yml
=> Change RD namespace to match flux config

environment-approvals.yml
Notes:
*  
*
*
Adding missing Immigration & Asylum app which should already have had AtO.
=> Adding ia-case-notifications-api

environment-approvals.yml
added missing CCD repositories
=> added missing CCD repositories

environment-approvals.yml
Enabling rd-user-profile-api and rd-profile-sync components to be deployed into prod.
=> Enabling user profile and profile sync for production

terraform-infra-approvals/global.json
=> Fix mispelling in infra approvals whitelist

terraform-infra-approvals/global.json
=> Infra approvals fixes

terraform-infra-approvals/ccd-shared-infrastructure.json
=> add elk module curator branch to test pipeline

terraform-infra-approvals/ccd-shared-infrastructure.json
=> Add Logstash/ELK Modules

team-config.yml
=> add in logstash product

team-config.yml, terraform-infra-approvals/ccd-logstash.json
=> Add in infra approval for logstash and slack mappings

terraform-infra-approvals/cmc-shared-infrastructure.json
Add CMC WAF in Prevention mode branch
=> add cmc-shared-infrastructure.json

terraform-infra-approvals/cnp-plum-recipes-service.json
=> Add temporary local exclusion for plum api management.

environment-approvals.yml
- Added bulk scan payment processor to approval list as it needs to be deployed to production.
=> Added bulk scan pay processor to approval list

team-config.yml
cnp-module-ase failing due to core-compute Product  missing from here
=> Adding core-compute

team-config.yml
=> EM-2110: Alter team config for evidence management em namespace

terraform-infra-approvals/div-shared-infrastructure.json
To allow `git@github.com:hmcts/cnp-module-waf?ref=ccd/CHG0033576`
Notes: copied global.json and added the extra rule
=> Added TF approvals file

cac-prod.yml, jobdsl/organisations.groovy, playbook.yml, team-config.yml
~Breaking change 🙊: namespace rename~
Including `send-letter-client` into BSP configs
=> Update config for BSP

team-config.yml
=> Use bar namespace for bar

terraform-infra-approvals/ccpayfr-shared-infrastructure.json
=> PAY-2213:AKS Migration changes

terraform-infra-approvals/ccpayfr-shared-infrastructure.json
=> Remove exclusion as it needs extra approval

terraform-infra-approvals/ccd-elastic-search.json
=> add in elk approval

jobdsl/organisations.groovy
=> Add data-generator to platform team

terraform-infra-approvals/ccd-elastic-search.json
Reverts hmcts/cnp-jenkins-config#341
=> Revert "added RDM-6000 branch temporarily to test elk changes"

team-config.yml
=> Create dm namespace

team-config.yml
=> Rename coh namespace

cac-prod.yml, jobdsl/organisations.groovy
New service has been onboarded partially on BSP flag. New team ideally should tackle it but saving the hassle
=> Add `blob-router-service`

cac-prod.yml, jobdsl/organisations.groovy, playbook.yml, team-config.yml
=> Add Management Information Jenkins Organisation

terraform-infra-approvals/cnp-idam-master.json
1.5 IDAM release 
Notes:
* Adds approvals for cnp-idam-master 
* https://github.com/hmcts/cnp-idam-master/tree/SIDM-3261-tf-approvals
=> chore(cnp-idam-master): add approvals for cnp-idam-master

terraform-infra-approvals/cnp-idam-master.json
Please note that the exception for modules/module-scaleset has NOT worked. See https://build.platform.hmcts.net/job/HMCTS_IDAM/job/cnp-idam-master/view/change-requests/job/PR-34/12/console
Notes:
* Extension of https://github.com/hmcts/cnp-jenkins-config/pull/355
* Adds null_resource
* Adds azurerm_virtual_machine
=> IDAM 1.5 resource tf approvals

terraform-infra-approvals/cnp-idam-master.json
Notes:
* Extension of #355 #356
=> Idam 1.5 tf approvals

cac-prod.yml, cac-sandbox.yml
Update maximumAuthenticationLifetime to match what AAD's session length is (90 days)
https://github.com/jenkinsci/saml-plugin/blob/master/doc/CONFIGURE.md#configuring-plugin-settings
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime
=> Stop samlLogout loop

environment-approvals.yml
Notes:
Adding work-allocation project to the approved to production apps list
=> Add work-allocation to the approved app list

team-config.yml
=> change name for Expert UI

environment-approvals.yml
Notes:
https://tools.hmcts.net/jira/browse/BPS-891
* Add bulk scan payment processor
=> Add bulk scan payment processor

jobdsl/organisations-beta.groovy
A new organisations beta file is required whilst we transition to aks based jenkins. 
Notes:
* 
*
*
=> Created beta org file for aks jenkins

jobdsl/organisations.groovy
[AB#617](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/617)
Notes:
Migrated Pipeline-Test to the new organisations file.
=> Removed PipelineTest from old organisations file

terraform-infra-approvals/div-case-orchestration-service.json, terraform-infra-approvals/global.json
=> Add reverted TF 0.11 branch

terraform-infra-approvals/probate-shared-infrastructure.json
=> WAF Detection Mode

terraform-infra-approvals/probate-shared-infrastructure.json
=> fixed lint issue

terraform-infra-approvals/probate-shared-infrastructure.json
=> Probate Disable WAF Request 941330

cac-prod.yml
**JIRA link (if applicable)**
[AB#732](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/732)
**Change description**
Bump up jenkins-agent build to nodejs v12.x LTS / sig v1.3.0
Does this PR introduce a breaking change? (check one with "x")
[x ] Yes
[ ] No
=> prod build jenkins agents bumped to nodejs v12x LTS

jobdsl/organisations-beta.groovy
[AB#765](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/765) 
Notes:
* Moving to new naming convention for jenkins credential Id.
=> Moving to Github App implementation for beta Jenkins

environment-approvals.yml
=> add xui TCs repo

cac-prod.yml
=> Use aat-00 for master builds

team-config.yml
Added the pcq team entry as per instructions in https://hmcts.github.io/onboarding/team/#slack
=> Update team-config.yml file with a pcq team entry

jobdsl/organisations-beta.groovy
Added [name: 'PCQ', regex: 'pcq-.*'] to org list in file
=> Added organisation pcq to org list

jobdsl/organisations-beta.groovy
=> FPLA-1324 added adoption to org list

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
AKS Jenkins has been setup with Github App and secrets.
=> Moving XUI to build beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
Few others were moved out before as they use same org.
=> fixing xui repos

cac-prod.yml
=> Swap to 01 for staging

team-config.yml
=> FPLA-1324 added adoption to team config

cac-prod.yml
=> Switch staging to aat-00

terraform-infra-approvals/xui-shared-infrastructure.json
=> add xui terraform whitelist

playbook.yml
=> Update CSP for CCD tests

cac-prod.yml, cac-sandbox.yml, cac-test.yml
Resolves # . 
https://tools.hmcts.net/jira/browse/RPE-1183
[AB#819]
Notes:
*
*
*
=> Update jenkins agent image

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Swapping FPL to Beta jenkins

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Swapping BSP to beta

environment-approvals.yml
=> Add probateman db to prod approvals

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
Just changing it to alphabetical order.
=> Swap CTSC to build-beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
Notes:
* There was a permission issue with jenkins not being able to access docmosis vault which is now sorted.
=> Moving FPL to build-beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Moving div and cmc orgs to build beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Moved probate to the new Beta Jenkins

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Move access management to beta jenkins

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> fpl flipping game

CODEOWNERS, private-dns-config.yaml
=> Add private dns config. Update codeowners.

private-dns-config.yml
=> Disable idam sprod and saat private dns operations.

jobdsl/organisations-beta.groovy
=> Add nightly-dev branch for use to test changes

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Ref data build-beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
* It was never meant to be used
=> Remove hmctsdemo branch

cac-prod.yml
=> Swap to aat-01

terraform-infra-approvals/ccpay-functions-node.json
Committing this file for whitelisting Terraform changes for ccpay-functions-node
Notes:
*
*
*
=> Whitelist terraform changes

team-config.yml
=> Contact update for ccpay-functions

environment-approvals.yml
=> Add ia-aip frontend

environment-approvals.yml
add reform-scan-notification to prod
=> add reform-scan-notification to prod

private-dns-config.yml
=> Add ethosldata env to private dns config

terraform-infra-approvals/bulk-scan-shared-infrastructure.json
https://tools.hmcts.net/jira/browse/BPS-1183
Please refer JIRA ticket and SNOW https://mojcppprod.service-now.com/nav_to.do?uri=%2Fchange_request.do%3Fsys_id%3D40a371681bdc90d889070e9c5e4bcbf7 for details on the change.
=>  Used exclusion branch for REQUEST-920-PROTOCOL-ENFORCEMENT

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Swap IA to build-beta

jobdsl/organisations-beta.groovy, jobdsl/organisations.groovy
=> Moving fees pay to build-beta

jobdsl/organisations-beta.groovy
=> Add dg to evidence

jobdsl/organisations.groovy
commenting on purpose as no one owns the left over repos
=> disable rpa on build

jobdsl/organisations-beta.groovy
=> , :facepalm:

private-dns-config.yml
External-dns is now installed in preview
=> Switch off jenkins registration in preview

jobdsl/organisations-beta.groovy, team-config.yml
https://tools.hmcts.net/jira/browse/RDM-8368
=> adding new service manage-case-assignment under CDM for now

private-dns-config.yml
=> Enable Consul in Preview for VPN

environment-approvals.yml
=> Added new ecm repos

jobdsl/organisations-beta.groovy
=> fix PR branches as currently all probate branches are being scanned

terraform-infra-approvals/cnp-idam-master.json
https://tools.hmcts.net/jira/browse/SIDM-4096
idam whitelist update
To support 0.12 upgrade in cnp-idam-master.
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> SIDM-4096 - idam whitelist update

jobdsl/organisations-beta.groovy, terraform-infra-approvals/ecm-shared-infrastructure.json
Added ecm consumer infra approval
=> Added ecm consumer infra approval

jobdsl/organisations-beta.groovy
=> Exclude archived repos

environment-approvals.yml
Notes:
- To support PCQ-328 Build production pipeline in preparation for 28 May release
- PCQ Consolidation Service
- PCQ Backend
- PCQ Frontend
- PCQ Shared Infrastructure
JIRA
https://tools.hmcts.net/jira/browse/PCQ-328
=> PCQ-328: Add PCQ production approvals

terraform-infra-approvals/ccd-shared-infrastructure.json
For https://github.com/hmcts/ccd-shared-infrastructure/pull/66
=> RDM-2703-Alerts

README.md
=> Update README on Requirements

environment-approvals.yml
=> Update environment-approvals.yml for em-ICP

terraform-infra-approvals/ccd-logstash.json
=> add logstash git@github.com:hmcts/cnp-module-logstash.git?ref=jenkins-beta-update

terraform-infra-approvals/ccd-elastic-search.json
=> whitelist elk@Ethosldata

terraform-infra-approvals/reform-scan-shared-infra.json
* Details in https://tools.hmcts.net/jira/browse/BPS-1311
=> Whitelisted WAF branch containing exclusion for 920420

private-dns-config.yml
ci(idam): enable idam-saat and idam-sprod
=> ci(idam): enable idam-saat and idam-sprod

environment-approvals.yml
=> Remove em-showcase from prod approvals

jobdsl/organisations-beta.groovy, team-config.yml
Part of UCMC renaming ticket https://tools.hmcts.net/jira/browse/CMC-467
UCMC will be removed later in separate PR.
=> Added Unspec to org list

team-config.yml
=> Use docker agent to build plum + crumble

team-config.yml
=> Use docker agent for rpe applications

team-config.yml
Config to setup the Work allocation WA team
=> Setup WA team

jobdsl/organisations-beta.groovy
=> Setup WA organisation config

team-config.yml
=> Add registry override for camunda

team-config.yml
Notes:
* opt in for FPL to use k8s build agents. 
*
*
=> imp: move FPL to k8s agents

team-config.yml
Reverts hmcts/cnp-jenkins-config#515
=> Revert "imp: move FPL to k8s agents"

terraform-infra-approvals/idam-shared-infrastructure.json
https://tools.hmcts.net/jira/browse/SIDM-4643
Allow azurerm_monitor_scheduled_query_rules_alert resource type
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> SIDM-4643 - Allow azurerm_monitor_scheduled_query_rules_alert for idam-shared-infra

team-config.yml
Notes:
* Just BSP, will do reform-scan separately
=> Moving bsp to k8s agents

team-config.yml
Reverts hmcts/cnp-jenkins-config#519
=> Revert "Moving bsp to k8s agents"

terraform-infra-approvals/global.json
feat(cnp-module-redis): allow ref azurermv2
=> feat(cnp-module-redis): allow ref azurermv2

team-config.yml
Notes:
* Upgrading Finrem to JDK 11.0.8
=> Add k8s-agent to Finrem

team-config.yml
AB#1064
* changed few things to be more readable than product name.
=> Add application tag to team config

team-config.yml
=> Revert finrem docker jenkins agent

team-config.yml
=> Migrate RPE to Jenkins Docker agents

team-config.yml
=> Migrate BSP team to Jenkins Docker agents

team-config.yml
=> Update team-config.yml to use k8s agent for finrem

team-config.yml
=> Migrate fpla to jenkins docker agent

team-config.yml
We encountered some issues with the builds so let's unmigrate for a while.
=> Revert "Migrate fpla to jenkins docker agent"

team-config.yml
Corrected contact_channel to ref-data-support
Notes:
*
*
*
=> Corrected contact_channel to ref-data-support

team-config.yml
=> Revert rpe from k8s-agent

team-config.yml
=> Revert draft-store to VM Jenkins agents

team-config.yml
=> Revert k8s agents plum

team-config.yml
=> Move back CNP to jenkins k8s agents

team-config.yml
=> RPE k8s build agents

terraform-infra-approvals/cnp-owaspdependencycheck-database.json
* https://build.platform.hmcts.net/job/HMCTS_CNP/job/cnp-owaspdependencycheck-database/job/PR-7/2/console
=> whitelist owasp dependency check firewall rule

terraform-infra-approvals/bulk-scan-shared-infrastructure.json, terraform-infra-approvals/reform-scan-shared-infra.json
=> Change module

terraform-infra-approvals/ccd-shared-infrastructure.json
=> Whitelisted the azurermv2 modules for ccd shared infra

team-config.yml
=> Revert crumble to vm agent temporarily

team-config.yml
=> Move to VM agents for plum

environment-approvals.yml
Notes:
To support PCQ-715 Build production pipeline in preparation for 3rd November release.
* PCQ Loader
JIRA
https://tools.hmcts.net/jira/browse/PCQ-715
=> PCQ-715 Update to add pcq-loader application to prod approvals list.

environment-approvals.yml
=> Add AAC Repo to Approved Environments

environment-approvals.yml
Notes:
* IA Team achieved Tech Readiness Approval on 21st of October
* Release date on 5th of November
* [Tech Readiness Approval](https://tools.hmcts.net/confluence/display/RSTR/Immigration+and+Asylum+-+Rel+4.0.0+-+Home+Office+Integration+API+1)
=> add ia-home-office-integration-api to Production list

environment-approvals.yml
Notes:
* IA Case Payments API Production release
* [Tech Readiness Approval](https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1412040095&__ncforminfo=CCSUe8YrjctkCgFDIa6t1teGXMsyhJimp_HquEtJT88dgyeFrZiWJWvQ_aAb3054tRgqGPR4WrM=)
=> IA Case Payments API release

terraform-infra-approvals/reform-scan-shared-infra.json
Notes:
* add azurerm_private_endpoint
*
*
=> add azurerm_private_endpoint for reform scan shared infra

terraform-infra-approvals/global.json
=> whitelisting management lock and group tf resource

team-config.yml
=> Move rpe back to vm agents

environment-approvals.yml
Added FACT to environment approvals
=> Added FACT to environment approvals

environment-approvals.yml
Notes:
* Added location ref api and data load for prod deployment
*
*
=> Add location-ref-api and load for infra approvals

terraform-infra-approvals/cnp-plum-recipes-service.json
=> whitelisting postgres_tf branch for plum recipe db

team-config.yml
=> Replace rpe channel

team-config.yml
=> more reverts

jobdsl/organisations-beta.groovy, team-config.yml
Notes:
* added civil-damages to unspec team as a part of splitting the codebase
=> Added civil-damages product to unspec team

terraform-infra-approvals/wa-case-event-handler.json, terraform-infra-approvals/wa-shared-infrastructure.json
Whitelist require_session for servicebus in wa shared infra and case-event-handler
=> Whitelist require_session for servicebus in wa apps

terraform-infra-approvals/cnp-plum-recipes-service.json
=> Testing module changes

jobdsl/organisations-beta.groovy
=> s2s pattern to include java client

environment-approvals.yml, team-config.yml
=> SSCS-7330 Add SSCS MYA

terraform-infra-approvals/global.json
Add azurerm_monitor_action_rule_action_group
allows creation of rules for monitoring
=> Update global.json add azurerm_monitor_action_rule_action_group

jobdsl/organisations-beta.groovy, team-config.yml
=> Added cpo project config

environment-approvals.yml
https://tools.hmcts.net/jira/browse/RBC-7423
Notes:
* Above is the ticket for ATO
=> Added in HRS repos

team-config.yml
Updating Fees & pay contact channel
Notes:
*
*
*
=> updating_fees&pay_contact_channel

jobdsl/organisations-beta.groovy
Adding new jenkin job for Send-letter KEDA containers
=> DTSBPS-484: Adding new jenkin job for Send-letter KEDA containers

jobdsl/organisations-beta.groovy
Regression in https://github.com/hmcts/cnp-jenkins-config/pull/477
=> Fix ethos Jenkins credential ID

environment-approvals.yml
Notes:
* Add caseworker service for production release
* https://tools.hmcts.net/jira/browse/RDCC-2692
=> Add caseworker repo for production release

environment-approvals.yml
Notes:
* Production deployment for RAS services
* https://tools.hmcts.net/jira/browse/AM-1294
=> Add RAS repos for production release

team-config.yml
Notes:
Adding the VH team config to allow jenkins build
=> Adding VH team config

jobdsl/organisations-beta.groovy, team-config.yml
=> RDM-12276 Added HMC Project Config

terraform-infra-approvals/camunda-bpm.json
=> Whitelist elastic search for camunda

terraform-infra-approvals/global.json
Wrong resource added in https://github.com/hmcts/cnp-jenkins-config/pull/602
=> Remove management group whitelist

terraform-infra-approvals/cnp-idam-master.json, terraform-infra-approvals/idam-master.json
removed idam-master.json as its cnp-idam-master.json
Notes:
*
*
*
=> SIDM-5939: its cnp-idam-master not idam-master

jobdsl/organisations-beta.groovy
The regex is not needed as per Tim's comment.
=> Remove regex in FPRL organisation

terraform-infra-approvals/ccpay-refunds-app.json
**Notes**:
A new file named ccpay-refunds-app.json is created to get approval for accessing a resource for 
https://github.com/hmcts/ccpay-refunds-app repo
JIRA: https://tools.hmcts.net/jira/browse/PAY-4644
=> ccpay-refunds-app.json added

environment-approvals.yml
Notes:
* IA Case Access API release
* Tech Readiness Approval [Immigration+and+Asylum+-+Rel+5.0.0+-+PBA](https://tools.hmcts.net/confluence/display/RSTR/Immigration+and+Asylum+-+Rel+5.0.0+-+PBA)
=> IA Case Access API release

environment-approvals.yml
case-document-am-api on prod. Please find SecOps approval in RDM-11107 attachment.
https://tools.hmcts.net/jira/browse/RDM-11107
=> ccd-case-document-am-api production approval

environment-approvals.yml
=> fixing url (ccd-case-document-am-api)

environment-approvals.yml
cpo-case-payment-orders-api on prod. Please find SecOps approval in CPO-58 attachment.
https://tools.hmcts.net/jira/browse/CPO-58
=> cpo-case-payment-orders-api production approval

private-dns-config.yml
removing idam-sprod
Notes:
*
*
*
=> SIDM-6057: removing idam-sprod

team-config.yml
=> Add Log and Audit (LAU)

terraform-infra-approvals/ccd-shared-infrastructure.json
Whitelists ta_native_versioning for cnp-module-storage-account for testing on ITHC
=> Sa versioning whitelist

jobdsl/organisations-beta.groovy
=> adding LAU to orgs list

terraform-infra-approvals/global.json
Troubleshooting json issue on em-native-pdf-anotator-app build
=> Whitelist json-troublshooting branch for testing issues on postgres module

terraform-infra-approvals/cnp-idam-master.json
Required for [SIDM-6318](https://tools.hmcts.net/jira/browse/SIDM-6318)
=> Add azurerm_postgresql_configuration for master

team-config.yml
Adding DA namespace to Jenkins Config
=> Add Domestic Abuse to Jenkins configuration

jobdsl/organisations-beta.groovy
=> DTSPO-5506 adding new ORG

environment-approvals.yml
Notes:
*
*
*
**CR Number : CHG5005870**
=> Update in environment-approvals.yml for Refunds Production Release

jobdsl/organisations-beta.groovy, team-config.yml
- adding new lab
- update
- updated
Notes:
*
*
*
=> DTSPO-5506 updated labs ORG

team-config.yml
Notes:
* Add Employment Tribunals
*
*
=> Add Employment Tribunals

jobdsl/organisations-beta.groovy, team-config.yml
Updated namespace for domestic abuse
=> Namespace update for Domestic Abuse

team-config.yml
=> DTSPO-5498 - Using ubuntu agent for no fault divorce team

environment-approvals.yml
=> Adding General Applications Service and CCD Definition projects

team-config.yml
=> Using ubuntu agent for reference data team

team-config.yml
=> "DTSPO 5499 Removed Team specific agent" 

team-config.yml
=> Pin agent to centos to test pipeline failures.

team-config.yml
=> Revert div-agent ubuntu

team-config.yml
=> Revert civil team agent to centos

team-config.yml
=> added div-agent centos

team-config.yml
=> SSCS Switch to centos agent

terraform-infra-approvals/ccd-elastic-search.json
=> Add CCD branch for cnp-module-elk

environment-approvals.yml
Notes:
* Added idam-user-dashboard project
=> SIDM-6645 - Added idam-user-dashboard

team-config.yml
Updated adoption slack channel name
Notes:
*
*
*
=> Updated adoption slack channel name

environment-approvals.yml
Add Log and Audit repositories.
Log and Audit successfully completed Tech Readiness review on Wednesday 23rd Feb and has AtO email approval from Ash Patel. Can send if required - Dave Jones, Tech Lead.
=> LAU-316 Add LAU repos

jobdsl/organisations-beta.groovy
cmc legal rep frontend is closed. So, removing it from dashboard.
=> CMC legal rep to be removed from dashboard

environment-approvals.yml
New frontend app production access request
Notes:
*
*
*
=> New frontend app production access request

jobdsl/organisations-beta.groovy
Notes:
Trying to add rpts group and rpts-frontend / rpts-backend items based on github repos
=> adding jenkins group for rpts

environment-approvals.yml
=> cpo prod access

terraform-infra-approvals/bulk-scan-shared-infrastructure.json
Add common tags module to bulk-scan-shared-infrastructure
=> DTSPO-4471 - Add common tags to bulk scan infra

terraform-infra-approvals/bulk-scan-shared-infrastructure.json
Just noticed random space between bracket and comma
=> DTSPO-4471 - Fix bulk-scan typo

jobdsl/organisations-beta.groovy, team-config.yml
=> Modify org name for family integration stream

team-config.yml
=> Updating application tag name per OCGI recommendation

jobdsl/organisations-beta.groovy, jobdsl/organisations-cnptest.groovy
https://tools.hmcts.net/jira/browse/DTSPO-7559
added topics to all platform and cnp repositories:
e.g. https://github.com/hmcts/service-auth-provider-app/
```
#!/usr/bin/env bash
function addTopic() {
gh repo edit --add-topic team-platform hmcts/$1
}
addTopic camunda-bpm
addTopic camunda-shared-infrastructure
addTopic draft-store
addTopic rpe-pdf-service
addTopic rpe-shared-infrastructure
addTopic service-auth-provider-app
addTopic service-auth-provider-java-client
addTopic cnp-database-subnet-whitelisting
addTopic cnp-keda-shared-infrastucture
addTopic cnp-module-adf 
addTopic cnp-module-automation-account
addTopic cnp-module-elk
addTopic cnp-module-key-vault
addTopic cnp-module-postgres
addTopic cnp-module-redis
addTopic cnp-owaspdependencycheck-database
addTopic cnp-plum-batch
addTopic …
```
=> DTSPO-7559 Introduce topics support

jobdsl/organisations-beta.groovy, jobdsl/organisations-cnptest.groovy
Can't fully test this locally because my suppliers laptop MITM's me preventing proper testing
=> DTSPO-7559 Add additional values required for xml config

jobdsl/organisations-beta.groovy, jobdsl/organisations-cnptest.groovy
I fixed this upstream: https://github.com/jenkinsci/github-branch-source-plugin/pull/529
=> DTSPO-7559 Remove duplicate xml

environment-approvals.yml
Added the git repositories for Private law
=> Added Private law for approval

environment-approvals.yml
Private Law: Adding shared infra to be accessible to Prod
=> Private Law: Adding shared infra to be accessible to Prod

terraform-infra-approvals/global.json
temporarily add branch with required providers needed to complete DTSPO-6371
=> DTSPO-6371 - temporarily add branch with required providers

environment-approvals.yml
=> Updated Adoption repos to whitelist

jobdsl/organisations-beta.groovy, jobdsl/organisations-cnptest.groovy
https://tools.hmcts.net/jira/browse/DTSPO-7559
Plan to merge in the morning
=> DTPSO-7559 Switch to 2 folders

jobdsl/organisations-beta.groovy
I think it needs to be in an 'all of' to make what I had before work, just reverting this to simplify it
=> DTSPO-7559 Remove skip on initial index

jobdsl/organisations-beta.groovy
(I'll test this locally and announce before merging)
=> DTSPO-7559 Split folders alphabetically

team-config.yml
Notes:
Part of ticket WLTS-7 Create a repository for the Translation Service
=> WLTS-7 Add ts to the team config

team-config.yml
Notes:
As per https://tools.hmcts.net/jira/browse/DTSPO-7853, Updated Hearings Management Interface tags to match agreed tag name within tagging dictionary - https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4
=> updated Hearings Management Interface tag to match tagging dictionary

terraform-infra-approvals/draft-store.json
=> Temporary whitelist key vault branch for draft-store

team-config.yml
Notes:
As part of https://tools.hmcts.net/jira/browse/DTSPO-8026 I have updated the tags for work-allocation to match what has been agreed within the tagging dictionary - https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary.
=> updated work allocation tag to match tagging dictionary

terraform-infra-approvals/sscs-tribunals-api.json
=> SSCS-10510 Whitelist service bus queue sessions

team-config.yml
=> Removed Family Private law - old config

terraform-infra-approvals/sscs-shared-infrastructure.json
=> sscs-remove-default-provider

environment-approvals.yml
Notes:
This is for Employment Tribunals Release 1.0
https://tools.hmcts.net/confluence/display/RSTR/ET-Rel-1.0.0+-+Release+Dashboard
CR: CHG5008762
=> Add Employment Tribunals repos

environment-approvals.yml
Notes:
* JIRA https://tools.hmcts.net/jira/browse/LAU-454
* Production release Wednesday 27th
=> LAU-454: Enable Case Disposer Production Pipeline

environment-approvals.yml
In preparation for CHG5008835.
=> Approve Translation Service for Production

private-dns-config.yml
Reverts hmcts/cnp-jenkins-config#779
=> Revert "Allow teams to opt-in to using zone with valid cert"

environment-approvals.yml, team-config.yml
Notes:
Initial configuration of sptribs project.
=> ST-432 Configuration of sptribs project

environment-approvals.yml
This keyvault will be used for CourtNav gateway API
=> Adding fis-shared-infrastructure for the keyvaults creation

private-dns-config.yml
Added em-ccdorc in private-dns-config to resolve build failure.
=> Added em-ccdorc in private-dns-config

terraform-infra-approvals/sscs-hearings-api.json
type azurerm_servicebus_subscription_rule
Resolves # https://tools.hmcts.net/jira/browse/SSCS-10829
Notes:
* Should hopefully resolve Error matching resources: [{managed azurerm_servicebus_subscription_rule servicebus_subscription_rule_sscs {azurerm } {service-bus.tf 37}}]
* Related https://github.com/hmcts/sscs-hearings-api/pull/325/files
=> add to resources

terraform-infra-approvals/global.json
=> Whitelist DB replicas branch

team-config.yml
=> Remove old fis configuration

private-dns-config.yml
Notes:
* Add div-case-orchestration-service to private dns config
*
*
=> Add div-case-orchestration-service to private dns config

private-dns-config.yml
Callbacks error from AAT environment to Preveiw Environment for general Application
Notes:
*
*
*
=> CIV-4438: Added civil-general-applications for DNS resolving

terraform-infra-approvals/dtsse-shared-infrastructure.json
=> Add Role Assignment module to DTSSE approvals

terraform-infra-approvals/dtsse-shared-infrastructure.json
=> Add azurerm_postgresql_firewall_rule to DTSSE shared infra

terraform-infra-approvals/probate-shared-infrastructure.json
=> added permission for azurerm_storage_management_policy

private-dns-config.yml
=> SSCS-10844 Add sscs private dns config

team-config.yml
Updating slach contact_channel for IDAM team.
=> SIDM-8077: Update tags for infrastructure resources

environment-approvals.yml
=> SSCS-11017 Add sscs-hearings-api approval

terraform-infra-approvals/probate-shared-infrastructure.json
=> added azurerm_storage_account_network_rules

environment-approvals.yml
update environment-approvals.yml for sptribs-case-api
https://tools.hmcts.net/jira/browse/ST-385
=> update environment-approvals.yml for sptribs-case-api

terraform-infra-approvals/ccd-shared-infrastructure.json
https://tools.hmcts.net/jira/browse/DTSPO-8276
Add branch of adf module to test it's working
Will be removed in subsequent PR
```
[ ] Yes
[x] No
```
=> DTSPO-8276 - test adf module branch

private-dns-config.yml
Notes:
* Adding civil-service so that our endpoint can receive callbacks from AAT.
*
*
=> added civil-service to opt in

private-dns-config.yml
Reverts hmcts/cnp-jenkins-config#829
=> Revert "added civil-service to opt in"

environment-approvals.yml
Notes:
* Private-law onboarding
*
*
=> Private law citizen journey onbaording

private-dns-config.yml
Notes:
* We hope to merge this some time tomorrow together with URL changes in civil service. 
* Once I know the time, I will leave a comment. 
* Please do not merge beforehand.
=> Add civil service

private-dns-config.yml
Notes:
* Adding civil-ccd-definition.
=> added ccd to gain new domain

terraform-infra-approvals/camunda-shared-infrastructure.json
=> DTSPO-11875 Update camunda-shared-infrastructure.json 

private-dns-config.yml
Notes:
* Fix name of repository in PR.
*
*
=> Self sign for civil ccd fix

team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-11788
Add owaspdependency product to team config so pipeline can be updated to use withInfraPipeline
=> DTSPO-11788 - owaspdependency

private-dns-config.yml
Notes:
* Remove ccd from list.
* There are issues that need resolving - we'll try at a later date to stop from blocking release.
*
=> Remove ccd

terraform-infra-approvals/camunda-shared-infrastructure.json
Reverts hmcts/cnp-jenkins-config#837
=> Revert "DTSPO-11875 Update camunda-shared-infrastructure.json "

private-dns-config.yml
Notes:
* Added civil-ccd to repos using new URL domain
*
*
=> added civil-ccd to repos using new URL domain

terraform-infra-approvals/draft-store.json
add module terraform-module-postgresql-flexible to draft-store
=> add module terraform-module-postgresql-flexible to draft-store

terraform-infra-approvals/draft-store.json
Reverts hmcts/cnp-jenkins-config#845
=> Revert "add module terraform-module-postgresql-flexible to draft-store"

terraform-infra-approvals/civil-sdt-gateway.json
=> whitelist azurerm_key_vault_access_policy

terraform-infra-approvals/draft-store.json
=> Point to new p14 DB

environment-approvals.yml
=> add fis-hmc-api to prod approval

terraform-infra-approvals/probate-shared-infrastructure.json
https://tools.hmcts.net/jira/browse/DTSSE-2832
[cnp-module-metric-alert](https://github.com/hmcts/cnp-module-metric-alert) requires updating
=> Include metric alert branch for testing in approvals.

private-dns-config.yml
=> Move s2s to .platform.hmcts.net

private-dns-config.yml
=> Move pdf-service to .platform.hmcts.net

terraform-infra-approvals/draft-store.json
=> Re-create new draftstore DB

private-dns-config.yml
=> Move camunda to .platform.hmcts.net

team-config.yml
=> DTSPO-12024 - Update slack channels

private-dns-config.yml
=> Move crumble to .platform.hmcts.net

environment-approvals.yml
=> DTSPB-2794 Add ccd data migration tool repo

private-dns-config.yml
Remove unused consulactive property
=> Change sbox zonetemplate to .platform.hmcts.net

environment-approvals.yml
=> Adding new Work Allocation Repo for Private Law

private-dns-config.yml
https://tools.hmcts.net/jira/browse/EM-5050
Added in EM related product names for preview URL.
=> Added in EM related product names

private-dns-config.yml
https://tools.hmcts.net/jira/browse/EM-5050
Added in EM related product name for preview URL.
=> Em 5050 add em api preview

private-dns-config.yml
Notes:
* This update is implemented for deprecated configuration of et product components which are et-sya, et-sya-api, et-cos
*
*
=> DNS Configuration Updates for Employment Tribunals

private-dns-config.yml
https://tools.hmcts.net/jira/browse/ST-1102
=> ST-1102-config update for sptribs

private-dns-config.yml
=> config update for sptribs (#869)

private-dns-config.yml
https://tools.hmcts.net/jira/browse/CIV-7118
Notes:
*
*
*
=> CIV-7118 Add General App CCD

environment-approvals.yml
=> Adding Notifications service for Go Live

private-dns-config.yml
https://tools.hmcts.net/jira/browse/PCQ-1643
Adding PCQ components
=> PCQ-1643 Adding pcq components

private-dns-config.yml
This change is to add lau and ccd-case-disposer
=> Lau-603 adding lau and ccd-case-disposer

environment-approvals.yml
=> DFPL-1240: Adding new jenkin job for FPL data migration tool

team-config.yml
stpribs project name update
https://tools.hmcts.net/jira/browse/ST-1089
=> ST-1089-stpribs project name update

team-config.yml
Reverts hmcts/cnp-jenkins-config#883
=> Revert "ST-1089-stpribs project name update"

team-config.yml
=> IJPS-20 add JPS team

private-dns-config.yml
Resolves "Usage of .internal URLs for preview and AAT Staging is deprecated" warning
=> Move dtsse to .platform.hmcts.net

private-dns-config.yml
=> Add NFD to platform hmcts net URL

private-dns-config.yml
Reverts hmcts/cnp-jenkins-config#889
=> Revert "Add NFD to platform hmcts net URL"

private-dns-config.yml
=> Add NFD services

private-dns-config.yml
=> Remove sptribs from components as its already in product

private-dns-config.yml
Move citizen ui to .platform.hmcts.net
=> Move citizen ui to .platform.hmcts.net

private-dns-config.yml
From JIRA:
https://tools.hmcts.net/jira/browse/DTSPB-3422
=> DTSPB-3422: added probate services as product

private-dns-config.yml
Notes:
To Fix https://tools.hmcts.net/jira/browse/RWA-2387.
=> RWA-2387: add wa services as product

terraform-infra-approvals/wa-shared-infrastructure.json, terraform-infra-approvals/wa-task-management-api.json
https://tools.hmcts.net/jira/browse/RWA-2101 deploying flexible server
Notes:
*
*
*
=> RWA 2101 added branch

terraform-infra-approvals/wa-shared-infrastructure.json, terraform-infra-approvals/wa-task-management-api.json
RWA 2101 Was wrong module
Notes:
*
*
*
=> changed to db

private-dns-config.yml
Notes:
*  Added finrem service
*
*
=> DFR-1917: update internal urls

terraform-infra-approvals/wa-shared-infrastructure.json, terraform-infra-approvals/wa-task-management-api.json
Changed the branch name I am using on perftest
Notes:
*
*
*
=> RWA-2101-change branch name

terraform-infra-approvals/ethos-repl-docmosis-service.json
Notes:
* Relates to testing DTPSO-13201
*
*
=> Allow cnp-module-webapp branch for ECM

environment-approvals.yml
https://tools.hmcts.net/jira/browse/ST-1095
=> ST-1095-environment-approvals.yml

private-dns-config.yml
JIRA: https://tools.hmcts.net/jira/browse/RDCC-6599
Notes:
*
*
*
=> RDCC-6599: update URLS for rd-caseworker-ref-api

private-dns-config.yml
Update internal url for Judicial Payment Solutions
=> IJPS-40: Update internal url for Judicial Payment Solutions

private-dns-config.yml
=> DTSRD-63: update URLs for all 'rd' products

private-dns-config.yml
https://tools.hmcts.net/jira/browse/CCD-4412
Replacing deprecated internal urls with up to date versions in jenkins and test files
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> CCD-4412: adding ccd, ts, hmc, aac, rpo

private-dns-config.yml
This change is to add ccd-case-disposer in private-dns-config.yml
=> Update private-dns-config.yml for ccd-case-disposer

terraform-infra-approvals/global.json
=> DTSPO-13423 - testing vnet provider branch for flexible server

private-dns-config.yml
=> Move prl-citizen to .platform.hmcts.net

private-dns-config.yml
Add nfdiv product name to private-dns-config
=> Add nfdiv product name to private-dns-config

private-dns-config.yml
Notes:
* Adds fpl-case-service to the changed dns settings.
https://tools.hmcts.net/jira/browse/DFPL-1249
=> DFPL-1249: Add fpl-case-service to dns config

private-dns-config.yml
=> Update CNC Citizen DNS Zone

private-dns-config.yml
=> Update DNS Zone

private-dns-config.yml
https://tools.hmcts.net/jira/browse/AM-2777
TLS Cert in Preview for AM
=> AM-2777 TLS Cert in Preview for AM - added AM to product list

private-dns-config.yml
=> Move ia to .platform.hmcts.net

private-dns-config.yml
Notes: Move claim store repo to platform.hmcts.net
=> move claim store to platform.hmcts.net

private-dns-config.yml
Added 'cpo' to zoneTemplate
Resolves # master build failure for cpo-case-payments-api (deprecated use of .internal)
Notes:
*
*
*
=> CCD-4479 : Update private-dns-config.yml - addition of cpo

private-dns-config.yml
- Removes fpl-case-service from config (due to below)
- Adds entire of fpl to dns config
=> DFPL-1431: Add entire fpl product to dns config

team-config.yml
Migrating Help with Fees to CFT
=> Adding help with fees

team-config.yml
=> Update team-config.yml for CUI Reasonable Adjustments

terraform-infra-approvals/civil-service.json
=> add config for whitelisting

private-dns-config.yml
Reported at https://hmcts-reform.slack.com/archives/C02P6LQ7E2U/p1685608778904419
=> Switch all teams to env.platform.hmcts.net

environment-approvals.yml
Add new idam-user-disposer service
=> Add new idam-user-disposer service

team-config.yml
=> Update team-config.yml for disposer

terraform-infra-approvals/disposer-shared-infrastructure.json
=> lau-626 terraform ifra apparoval for disposer-shared-infrastructure

environment-approvals.yml
=> adding civil orchestrator service

environment-approvals.yml
=> Rename idam disposer

terraform-infra-approvals/global.json
https://tools.hmcts.net/jira/browse/DTSPO-14238
=> DTSPO-14238 Add application insights module to approval list

environment-approvals.yml
https://tools.hmcts.net/jira/browse/DFPL-1618
- Enables the fpl-wa-task-configuration master pipeline to deploy our DMN tables into production in preparation for our WA release on 19th July/
=> DFPL-1618: Enable FPL DMN tables to be deployed to prod

team-config.yml
Resolves # https://tools.hmcts.net/jira/browse/PAY-6400
Notes:
* Updates Fee and Payments slack channel to be fee-pay-nightly-pipeline
* This applies to both BAR and CCPAY components.
=> Update to address Payment slack channel change

terraform-infra-approvals/wa-task-management-api.json
Update wa-task-management-api.json to test JIT in AAT
=> Update wa-task-management-api.json to test JIT in AAT

environment-approvals.yml
Add [help-with-fees-shared-infrastructure](https://github.com/hmcts/help-with-fees-shared-infrastructure/tree/master)
=> add help-with-fees-shared-infrastructure to environment-approvals.yml

environment-approvals.yml
Added civil-sdt and civil-sdt-gateway repositories to environment-approvals.yml.
=> SDT-161: Add SDT prod env approvals

deprecation-config.yml
=> Deprecate charts

team-config.yml
Onboard the majority of CFT teams to the Ardoq integration step of the pipeline
=> Onboard some teams to Ardoq integration

environment-approvals.yml
=> Adding CUI repo

deprecation-config.yml
updating config for chart-job to deprecate previous versions
Current version was created here https://tools.hmcts.net/jira/browse/DTSPO-15287
=> DTSPO-15294-Update-deprecation-config.yml

terraform-infra-approvals/global.json
https://tools.hmcts.net/jira/browse/DTSPO-15347 
In  order to test the module branch on civil-service repo added the branch here to complete the build on jenkins.
=> Updated global file to allow branch

terraform-infra-approvals/global.json
=> clean up after test done

team-config.yml
Need to quickly disable Ardoq until a new maintainer is found for the application.
=> Remove ardoq config

terraform-infra-approvals/global.json, terraform-infra-approvals/wa-task-management-api.json
Also allows dev branch for wa-task-management-api infra for debugging and testing
=> Whistlist SDP DB user module as global

deprecation-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-16165
Required to move teams to latest chart job changes - so we can then monitor adoption
Notes:
*
*
*
=> DTSPO-16165 Bump chart-job nagging version

deprecation-config.yml
=> Fix year for job nagger

deprecation-config.yml
* Update chart-job nagger version to 2.1.1
=> Chart-job to 2.1.1 in nagger

team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-14998
Added channel id for all the channels, the one where no channel id set are the one not found.
=> DTSPO-14998 - set channel id for team config

terraform-infra-approvals/civil-service.json
=> Add resource allowance to create Azure function app

terraform-infra-approvals/ecm-consumer.json
Notes:
* Adding ref to postgres module PR to test on ecm consumer DBs
* https://tools.hmcts.net/jira/browse/DTSPO-16806
=> Added ref to PR for testing change to postgres module

terraform-infra-approvals/ecm-consumer.json
Notes:
* changing ref to pr to test https://github.com/hmcts/terraform-module-postgresql-flexible/pull/58
=> Update pr ref for ecm-consumer postgres module

terraform-infra-approvals/civil-sdt.json
Notes:
* Testing change to servicebus namespace module - https://github.com/hmcts/terraform-module-servicebus-namespace/pull/38
=> Point civil-sdt to pr branch of servicebus-namespace module

terraform-infra-approvals/civil-sdt.json
Notes:
* Fixes syntax issue with #1037
=> Fix branch reference

terraform-infra-approvals/sscs-shared-infrastructure.json
Notes:
* Adding missing comma in #1039
*
*
=> Fixed syntax

.github/workflows/angular-update.yml, deprecation-config.yml, scripts/angular-version.sh
[DTSPO-15800](https://tools.hmcts.net/jira/browse/DTSPO-15800)
Adds:
- Automation which runs every month to update the version of Angular in support for our pipeline nagger
Builds on nagger config added in https://github.com/hmcts/cnp-jenkins-library/pull/1207 so that we don't have to touch this version
=> DTSPO-15800: Automate Angular Version Updates

deprecation-config.yml, scripts/angular-version.sh
=> DTSPO-15800: Add date update

terraform-infra-approvals/am-judicial-booking-service.json
Notes:
* Used to test this change: https://github.com/hmcts/terraform-module-postgresql-flexible/pull/58
* Relates to to https://tools.hmcts.net/jira/browse/DTSPO-16979
=> Testing new functionality in postgres flex module

team-config.yml
=> CUIRA-325 azure tags

deprecation-config.yml
Updating base, nodejs and java base chart version and setting date for nagger updates
=> Updating base, nodejs and java base chart version and setting date for nagger updates

terraform-infra-approvals/adoption-web.json
https://tools.hmcts.net/jira/browse/DTSPO-17012
Notes:
*
*
*
=> Adds exepmtion for data persistency branch on redis module

terraform-infra-approvals/cnp-plum-recipes-service.json
=> Allow plum to use redis data persistency test branch

terraform-infra-approvals/ccd-elastic-search.json
=> Add new branch to ccd-elastic-search.json

terraform-infra-approvals/ccd-elastic-search.json
=> DTSPO-17635 - Allow cnp-module-elk branch on ccd-elastic-search

team-config.yml
Notes:
* Adds team config entry for Docmosis
* Doing this in relation to https://tools.hmcts.net/jira/browse/DTSPO-14032 to allow use of tags module in new infra
=> Add team config entry for Docmosis

terraform-infra-approvals/docmosis-infrastructure.json
Notes:
* Testing changes made to Application Insight module
* Relates to https://tools.hmcts.net/jira/browse/DTSPO-14032
=> Test app insights module changes

team-config.yml
Notes:
* Removes any reference to arm agents in team-config.yml
=> Dtspo 17999 remove arm jenkins agents

terraform-infra-approvals/blob-router-service.json
Notes:
* Added azurerm_api_management_api_diagnostic for custom apim logging
=> Add blob router to infra approvals

terraform-infra-approvals/global.json
=> Adding branch for testing

environment-approvals.yml
=> Add new ET Repo

terraform-infra-approvals/global.json
https://github.com/hmcts/terraform-module-servicebus-subscription/pull/28/files
Notes:
*
*
*
=> 4.x servicebus subscription

terraform-infra-approvals/global.json
=> Add ASB 4.x

terraform-infra-approvals/bastion.json
Notes:
* Testing changes made to vm-bootstrap module in https://github.com/hmcts/terraform-module-vm-bootstrap/pull/67 
* https://tools.hmcts.net/jira/browse/DTSPO-18633
*
=> Update module_calls for bastion repo

terraform-infra-approvals/global.json
=> Add other ASB 4.x branches

terraform-infra-approvals/bastion.json
Notes:
* Testing updated module in bastion repo
=> Testing updated vm-bootstrap module

terraform-infra-approvals/bastion.json
https://tools.hmcts.net/jira/browse/DTSPO-18828
Changing feature branch back to master.
=> DTSPO-18828 - change feature branch back to master

team-config.yml
=> Fix  PCS config

terraform-infra-approvals/global.json
=> White list terraform-module-postgresql-flexible branch

terraform-infra-approvals/ccpay-bulkscanning-app.json
Update to allow 100% logging of the bulk-scanning-payments product, an updated endpoint using OAuth2 authentication.
Resolves # [PAY-7482](https://tools.hmcts.net/jira/browse/PAY-7482)
Notes:
* Update sampling percentage to 100% for the Payment Bulk Scanning API which is to use OAuth2 authentication.
* Payment Bulk Scannin is not a heavy use API, however the sampling change is important to ensure all requests are successful.
=> PAY-7482: Update ccpay-bulkscanning-app.json to update logger

environment-approvals.yml
Notes:
* Pre-requisite step for the release on Tuesday 14th Jan - CHG5019529
=> ADOP-2551: Enable Adoption migration tool in production

terraform-infra-approvals/em-icp-api.json
=> reources required azure web pub sub

team-config.yml
Relates to [HDPI-176](https://tools.hmcts.net/jira/browse/HDPI-176)
=> Adding enforcement service to jenkins config

team-config.yml
=> Adding the team-config for civil-citizen-ui

terraform-infra-approvals/em-hrs-api.json
em-hrs-api need to create private endpoints
=> EM-6549 and VIH-11296 add private endpoint resources for vh and cvp

terraform-infra-approvals/ccd-elastic-search.json
Added new resources to allow list
=> DTSPO-25565 - added resources to allow list for ccd

terraform-infra-approvals/ccd-elastic-search.json
Notes:
* Adds resources for new load balaancer to whitelisted resources
*
*
=> Update list of allowed resources on ccd-elastic-search

terraform-infra-approvals/global.json
Reverts hmcts/cnp-jenkins-config#1140
=> Revert "DTSPO-26253 - Allow testing of module branch"

terraform-infra-approvals/dtsse-shared-infrastructure.json
Resolves https://github.com/hmcts/dtsse-shared-infrastructure/pull/197
=> chore(dtsse_shared_infra): add private link resource types

terraform-infra-approvals/rpx-xui-webapp.json
Add azurerm_monitor_scheduled_query_rules_alert and azurerm_monitor_action_group resources to enable monitoring for the webapp
https://tools.hmcts.net/jira/browse/CME-717
Notes:
*
*
*
=> CME-717: feat(terraform): add monitoring resources to webapp config

terraform-infra-approvals/lau-eud-backend.json
https://tools.hmcts.net/jira/browse/LAU-1224
=> Whitelist random_password

terraform-infra-approvals/rpx-xui-webapp.json
get functionality from new api
https://tools.hmcts.net/jira/browse/CME-717
=> CME-717: Update rpx-xui-webapp.json

team-config.yml
=> add rota to jenkins config
