hmcts/cnp-jenkins-config

cac-prod.yml
Build monitors for master and nightly builds.
RDM-3264
=> Add CDM build monitors

cac-prod.yml
They follow: HMCTS_$team/$repo/$branch so adjust regex accordingly
=> Fix CDM build monitior regexes

cac-prod.yml
This change adds the latest I&A services `ia-case-documents-api` and `ia-case-notifications-api` to the I&A build monitor
=> updated IA dashboard via cac-prod.yml to include latest services

jobdsl/organisations.groovy
Not sure if this was intentional but allow Sandbox to still allow all
branches as it did previously.
=> Enable all branches on Sandbox

cac-prod.yml
Adding `cmc-citizen-frontend` to buildMonitor in preparation for nightly jenkins pipeline.
=> Add cmc-citizen-frontend to prod build monitor

cac-prod.yml
Adding missing CMC projects - MichaelO is taking care of adding nightly security scanning e.g.:
https://github.com/hmcts/cmc-claim-store/pull/764
=> Add legal-frontend and claim-store to prod

environment-approvals.yml
Notes:
* rpa-dg-docassembly-api is ready to be deployed to production alongside CMC
=> Enable rpa-dg-docassembly-api deployments to prod

terraform-infra-approvals/bulk-scan-processor.json, terraform-infra-approvals/global.json
* Bulk scan uses `azurerm_template_deployment` for api management.
* Adding it to the approval list as per the deprecation warnings raised on slack channel.
=> Added azure template deployment to approval list

environment-approvals.yml
Reverts hmcts/cnp-jenkins-config#315
Not needed yet on prod . Reverting it so that pipeline will skip deployment on prod
=> Revert "Added bulk scan pay processor to approval list"

terraform-infra-approvals/ccd-shared-infrastructure.json
Added a branch reference which puts CCD in Prevention mode with fixed list of excluded rules. https://tools.hmcts.net/jira/browse/RDM-3807
=> ccd-waf branch to infra approvals list

terraform-infra-approvals/idam-api.json, terraform-infra-approvals/idam-web-admin.json, terraform-infra-approvals/idam-web-public.json
https://github.com/hmcts/cnp-module-webapp/pull/156#discussion_r325772764
Notes:
* IDAM need this branch of the module to resolve several issues with the module execution see https://github.com/hmcts/cnp-module-webapp/pull/156
* It does not seem possible to merge these changes into master due to a number of constraints
* IDAM is completing ASE to AKS migration and this module/whitelist rule will not be needed in the future
**Deadline = 24/09/2019 00:00 AM**
=> SIDM-3180 feat(tf whitelist): add ref=SIDM-3089 for IDAM webapps

terraform-infra-approvals/ccd-elastic-search.json
I would like to test elk changes in the branch RDM-6000.  But sandbox environment is broken at the moment. So, temporarily added this to infra approvals list to test the elk changes in perftest environment.
=> added RDM-6000 branch temporarily to test elk changes

jobdsl/organisations.groovy, playbook.yml
Prevents clobbering of main prod jenkins status by other builds such as
nightly or sandbox
Tested on draft-store:
Prod jenkins main check isn't renamed at it's a required branch all over the place this will move everything else
=> Custom commit status per organisation

team-config.yml
Missed this config during #349 
Reference to the build: https://build.platform.hmcts.net/view/BSP/job/HMCTS_BSP/job/blob-router-service/job/master/1/console
=> Add reform-scan product in team-config

cac-prod.yml, jobdsl/organisations.groovy
Why?
Discussed in hmcts/blob-router-service#8, removed in hmcts/blob-router-service#9 and created new repository - hmcts/reform-scan-shared-infra to match the product
=> Add configs for `reform-scan-*`

team-config.yml
For this project separate managed identity was created under `reform-scan` name but config was not reflected after copying same block of `bsp`
=> Fix namespace for `reform-scan` "team"

environment-approvals.yml
Currently entry is missing to build infrastructure
Notes:
*
*
*
=> Added Bulkscanning App to allow build infra

terraform-infra-approvals/cnp-idam-master.json
Allow `cnp-module-consul?ref=0.1.6-idam-1.5`
Changes must be ignored for consul to prevent destruction during release to some environments
including production.
https://github.com/hmcts/cnp-module-consul/compare/0.1.6...0.1.6-idam-1.5
=> chore(idam): update cnp-idam-master whitelist

team-config.yml
Fixes build issue for the MI team.
=> Fixed namespace key spelling mistake for MI

playbook.yml
Resolves # issue with sauce-on-demand plugin for cross browser tests
A just-in-time binding to com.saucelabs.jenkins.pipeline.SauceConnectStep was already configured on a parent injector.
at org.jenkinsci.plugins.workflow.steps.ContextParameterModule.configure(ContextParameterModule.java:45)
=> updated sauce-on-demand plugin

environment-approvals.yml
- Added blob router and reform scan shared infrastructure to approval list as we need  to ITHC on prod environment.
- Traffic is not going to be live and this is just for ITHC testing so that we can do pen testing for crime VPN.
=> Added reform scan shared infra and blob router to deploy them into prod

cac-sandbox.yml
**JIRA link (if applicable)**
[AB#732](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/732)
**Change description**
Bump up jenkins-agent sandbox-build to nodejs v12.x LTS / sig v1.3.0
Does this PR introduce a breaking change? (check one with "x")
[x ] Yes
[ ] No
=> sandbox-build agents bumped to nodejs v12x LTS / sig img v1.3.0

terraform-infra-approvals/ccd-shared-infrastructure.json
Just adding this temporarily to allow for testing of module in perftest because it's already in a state to be tested there
=> Add test branch of module-waf to ccd-shared-infra

terraform-infra-approvals/bulk-scan-shared-infrastructure.json
- Temporarily adding exclusion to test pip upgrade branch https://github.com/hmcts/bulk-scan-shared-infrastructure/pull/160
- Changes  https://github.com/hmcts/cnp-module-palo-alto/pull/24 are not yet merged as it may impact other consumers of Palo module.
=> Added whitelisting for palo module branch for bulk scan shared infra

terraform-infra-approvals/reform-scan-shared-infra.json
Without pip upgrade, palo-alto module fails at terraform apply stage. Same change was required (and made) for bulk-scan-shared-infrastructure.
=> Add palo-alto module branch with upgraded pip to reform-scan tf approvals

cac-prod.yml
=> Fix regex for BSP config

terraform-infra-approvals/global.json
Until we manage to do the breaking change we may as well allow people to use 2.x
https://github.com/hmcts/cnp-module-key-vault/pull/22
=> Add 2.x azure terraform compatible key vault branch

terraform-infra-approvals/bulk-scan-shared-infrastructure.json, terraform-infra-approvals/reform-scan-shared-infra.json
* Previous pip upgrade branch changes have been merged to master now 
* `add-pdf-threat-exclusion` includes adding exclusion for PDF threat id 34805 https://github.com/hmcts/cnp-module-palo-alto/tree/add-pdf-threat-exclusion
More details are included here https://tools.hmcts.net/jira/browse/BPS-1117
* This exclusion is currently applied by Devops manually on palo instances so it is currently in prod and being approved by IA.
* We can't merge the exclusion change to master as it will apply to all the consumers of palo module.
* Also soon we are migrating to shared Palos so this should be just an interim solution.
=> Added PDF threat exclusion branch to reform and bulkscan

terraform-infra-approvals/bulk-scan-shared-infrastructure.json
Allow for using terraform-module-servicebus-queue branch with count parameter. The change in the module needs to be verified on a separate branch first, so that changes don't get deployed to aat and prod. Once that's done and the module is updated, this PR will be reverted.
=> Allow for using terraform-module-servicebus-queue branch with count param

terraform-infra-approvals/reform-scan-shared-infra.json
* Mistakenly used wrong exclusion branch previously which had exclusion for 3 rules and was used for bulk scan.
* Reform scan WAF only needs to exclude one rule 920420
=> Use exclusion branch containing exclusion only for 920420

terraform-infra-approvals/global.json
Notes:
* Related to cnp-core-infra cleanup ticket which uses vnet module
* https://github.com/hmcts/cnp-module-vnet
=> Add cnp-module-vnet to tf infra approvals

team-config.yml
Notes:
*
*
*
while k8 agents are having connectivity issues this is to revert finrem back to using the jenkisn agent to unblock our pipelines. It will be reverted back to K8 agents when their issues are resolved
=> temporarily revert finrem back to the jenkins agent

terraform-infra-approvals/pcq-shared-infrastructure.json
Resolves https://tools.hmcts.net/jira/browse/PCQ-678.
Notes:
* PCQ Blob Storage requires all blobs to expire (be deleted) after 90 days.
* Terraform change adds rule azurerm_storage_management_policy to allow PCQ to manage expiration rules.
=> PCQ-678: Update to allow PCQ to add lifecycle rules to blob storage.

terraform-infra-approvals/bar-shared-infrastructure.json
58:25  this repo is using a terraform resource that is not allowed,
**16:58:25  whitelists are stored in https://github.com/hmcts/cnp-jenkins-config/tree/master/terraform-infra-approvals
16:58:25  send a pull request if you think this is in error.
16:58:25  non whitelisted resources:**
16:58:25  ```
16:58:25  error loading module [.]: Invalid argument name: Argument names must not be quoted. (and 1 other messages)
16:58:25  Error loading infra definition at .
=> PAY-3742: Whitelisting for Bar shared infrastructure

terraform-infra-approvals/global.json
Notes:
I'd like to use the azurerm_monitor_action_group to enable monitoring functionality
*
*
*
=> Allow azurerm_monitor_action_group module

environment-approvals.yml, team-config.yml
SSCS COR Service no longer being renamed to MYA. Reverting Change
Notes:
*
*
*
=> Revert "SSCS-7330 SSCS MYA (#606)"

jobdsl/organisations-beta.groovy
* It deletes branches/ PRs which are not updated in last 30 days from Jenkins
* Doesn't apply for Jenkins as it's a valid scenario.
=> Ignore stale branches from getting built

jobdsl/organisations-beta.groovy
* Had a failure this morning with Jenkins Library pipeline Test as shared-infra repo wasn't touched for more than a month.
=> Skip aged ref for library test

environment-approvals.yml
WA is a set of backend APIs offering a common capability.  This currently all sits behind a feature flag in LD called: `wa-task-initiation-feature` for the Work Allocation project configured to be false.
The AtO is an extension to the existing IAC Service team AtO. 
AtO: https://tools.hmcts.net/jira/browse/RBC-7654?src=confmacro
=> Adding WA apps and iac camunda config for WA Deployments.

terraform-infra-approvals/idam-master.json
Required as new AKS cluster is routed through the new firewalls, this
allows the FR subnets to use the correct route back to AKS
Notes:
*
*
*
=> SIDM-5937: Allowing idam-master to control routes

terraform-infra-approvals/idam-master.json
Missed azurerm_subnet_route_table_association from vnet.tf subnet
assignments
Notes:
*
*
*
=> SIDM-5937: missed one

environment-approvals.yml
Adding am-role-assignment-refresh-batch service for production deployment.
Notes:
* SecOps approval is attached in the JIRA ticket https://tools.hmcts.net/jira/browse/AM-1430
=> Add am-role-assignment-refresh-batch for prod

jobdsl/organisations-beta.groovy
This will exclude the hmi-case-hq-emulator repo as it is on SDS
=> Exclude the case hq emulator repo

jobdsl/organisations-beta.groovy
Notes:
* The current Employment Tribunals org is incorrectly including the ethos-repl-docmosis repo. The regex needs to change to only pick up repositories beginning with "et-"
*
*
=> Update Employment Tribunals to only pick up 'et-' repos

team-config.yml
Notes:
* Switch to Ubuntu agent due to Playwright tests not running correctly on standard agent
=> Using Ubuntu agent for IDAM

team-config.yml
Notes:
* This change will be reverted once the CCD Node.js components have been updated to use Node.js version 14 - see CCD-2332 (https://tools.hmcts.net/jira/browse/CCD-2332).
=> Temporarily switch CCD build agent back to centos

jobdsl/organisations-beta.groovy, team-config.yml
It has been agreed technically that Domestic Abuse and Child arrangement under PrivateLaw project will use the same codebase. Therefore DA specific configuration is no longer required. Hence, removing Domestic Abuse Jenkins configuration
=> Off boarding Domestic abuse

environment-approvals.yml
**Notes:**
1) This will be standard CICD deployment for new ref data application mentioned in file with LD Toggled OFF and no service 
whitelisted in production.
2) This is being agreed with plats ops team (Benjamin.Neill@HMCTS.NET),  perftest , ITHC and Release team.
3) That OAT and ATO will be part final release when EXUI consumer go live with us in near future.
Please approve this PR.
Thanks.
=> RDCC-4064 adding common data repo approvals

environment-approvals.yml
Added adoption-shared-infrastructure repo to prod whitelist
Notes:
*
*
*
=> Added adoption-shared-infrastructure repo to prod whitelist

terraform-infra-approvals/global.json
Allowing common tags to be used globally
=> DTSPO-6371 - allow hmcts/terraform-module-common-tags

terraform-infra-approvals/global.json
not needed on Jenkins use var.common_tags
=> Remove common tags module

terraform-infra-approvals/camunda-shared-infrastructure.json
Added elk RDM-13038 to whitelist for Camunda.
Notes:
*
*
*
=> added extra source to camunda shared infra

terraform-infra-approvals/global.json
Adding DTSPO-6371_azurerm_upgrade branch on terraform-module-servicebus-queue to global allow list whilst working on DTSPO-6371. This is needed to test upgrading to azurerm 3.x.x
=> DTSPO-6371 - add service bus queue module

team-config.yml
Notes:
As per https://tools.hmcts.net/jira/browse/DTSPO-7842 and the tagging dictionary the application tag for Camunda has been updated.
=> updated camunda to use tag of core as per tagging dictionary

team-config.yml
Notes:
For https://tools.hmcts.net/jira/browse/DTSPO-7842 and as per https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary application name has been updated.
=> updated tag name for family-integration as per tagging dictionary

team-config.yml
Notes:
As per https://tools.hmcts.net/jira/browse/DTSPO-7853, Updated Family Private Law tags to match agreed tag name within tagging dictionary - https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4
=> updated Family private Law tag to match tagging dictionary

team-config.yml
Notes:
Updated application tag for snl to match agreed name in the tagging dictionary - https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary
=> updated snl tag to match agreed tag within tagging dictionary

terraform-infra-approvals/global.json
=> DTSPO-6371 - delete old branches of servicebus modules

environment-approvals.yml
This is to include ia-bail-case-api into the scope.
=> Updates to include ia-bail case api service

team-config.yml
Updating team name to "Platform Operations" according to DTSPO-8049
=> DTSPO-8049 - updating team name for keda

environment-approvals.yml
Notes:
* https://tools.hmcts.net/jira/browse/DTSPO-8117
* Whitelisting for creating prod resources for plum
=> Adds plum to approvals for prod, for testing cluster/traefik upgrades

terraform-infra-approvals/global.json
Websockets are not currently supported by Azure Frontdoor so it is not possible to host a websocket server inside the CNP. This PR allows the use of [Azure Web Pub Sub](https://azure.microsoft.com/en-us/products/web-pubsub/) so that websocket servers can be created as part of the CNP infrastructure pipelines
=> Add azurerm_web_pubsub to support websockets

terraform-infra-approvals/global.json
Notes:
*. In order to allow  testing adding-postgresql-ad-administrator branch
=> allowed adding-postgresql-ad-administrator branch

terraform-infra-approvals/dtsse-shared-infrastructure.json
Notes:
* This is to allow this PR to run: https://github.com/hmcts/dtsse-shared-infrastructure/pull/11/files 
* This is needed for the dtsse-ardoq-adapter to run in ptl-intsvc but use our teams central KV
=> Allows DTSSE shared infra repo to modify the KV access policy

environment-approvals.yml
grafana and postgres are disabled in prod via tfvars.
This is needed to allow https://github.com/hmcts/dtsse-ardoq-adapter/ to be deployed to prod later
=> Deploys a DTSSE KV to prod

private-dns-config.yml
Fixes the component name as for civil-ccd it doesn't match the repository name.
Repository name: civil-ccd-definition
Component name: civil-ccd
Value should be: civil-ccd
=> Fix component name for civil-ccd

terraform-infra-approvals/div-case-orchestration-service.json
Creating a seperate approval file as div-shared-infra isn't passing to div-cos for v14 changes
=> add div-cos to allow for v14 postgres branch

team-config.yml
Update team-config.yml so crumble build notices channel is set to test channel where jenkins bot has not been invited.
To be used to test change to jenkins library that will fail pipelines when the bot is not in the channel.
=> DTSPO-7637 - Update team-config.yml

team-config.yml
Reverts hmcts/cnp-jenkins-config#875
restore plum slack channel to platops-build-notices now that DTSPO-7637 is complete
=> Revert "DTSPO-7637 - Update team-config.yml"

terraform-infra-approvals/sscs-shared-infrastructure.json
Notes:
* Follow up from #868 
*
*
=> Whitelist cnp-module-storage-account for sscs-shared-infrastructure

environment-approvals.yml
Notes:
*https://tools.hmcts.net/jira/browse/DFR-1944
These two repo had been absorb in finrem-case-orchestration-service service.
Fully decommission finrem-document-generator-serivce and finrem-evidence-management-client-service 
Archive githup repos
Remove from Jenkins dashboards
Remove from Jenkins pipeline builds
Ensure pods are not deployed in all envs
=> DFR-1944: Fully decommission dgcs and emcs for FR

terraform-infra-approvals/sscs-shared-infrastructure.json
Whitelist the `fix/private-endpoint-provider` branch of cnp-module-storage-account for sscs-shared-infra
=> Whitelist fix branch for sscs-shared-infra

environment-approvals.yml
DFR-1997: decommission-notification-service
Notes:
* This service has been absorb by finrem-case-orchestration-service.
*
*
=> DFR-1997: decommission-notification-service

environment-approvals.yml
Notes:
Add Special Tribunals repos in scope of Release 1.0:
https://tools.hmcts.net/confluence/display/RSTR/Special+Tribunal+Release+1.0.0+Release+Dashboard
CR: CHG5011837
=> Add Special Tribunals repos

terraform-infra-approvals/dtsse-shared-infrastructure.json
Need this extension for the dtsse postgres db that has the grafana data on it. Looks like it was manually added to the existing postgres db so I'd like to add it to tf for the flexi one
=> Allow azurerm_postgresql_flexible_server_configuration on dtsse

deprecation-config.yml
Will be used in conjunction with https://github.com/hmcts/cnp-jenkins-library/pull/1125 
to allow us to specify dependencies in build.gradle file to deprecate as well as helm charts that apps depend on.
=> DTSPO-14461  Add option to specify gradle dependencies

terraform-infra-approvals/xui-shared-infrastructure.json
This whitelists a branch of the cnp-redis-module which sets up a new private endpoint for redis. This is currently for test purposes only
=> Whitelist redis module branch

team-config.yml
Merging this PR will onboard NFDIV to Ardoq meaning the "Tech Stack" step will now send data to Ardoq. 
Currently this only affects the frontend app (tested here https://github.com/hmcts/nfdiv-frontend/pull/3270) but will also onboard the backend app once this https://github.com/hmcts/cnp-jenkins-library/pull/1162 is merged. 
Backend tested here: https://github.com/hmcts/nfdiv-case-api/pull/3257/
=> Adds ardoq application_id for NFDIV

team-config.yml
Notes:
* Just because the slack channel in there is dead/dormant
=> Change et slack channel

terraform-infra-approvals/ecm-consumer.json
Notes:
* Added for testing pr branch on terraform-module-postgres-flexible
* https://github.com/hmcts/terraform-module-postgresql-flexible/pull/58 
* No longer required as team have completed migration
=> Remove ecm-consumer file as no longer required

deprecation-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-15800
Adds angular/core version to deprecation map, and by extension enables us to track other npm dependencies in the future too
In junction with https://github.com/hmcts/cnp-jenkins-library/pull/1207/files
Uses some generic date for now until we have a need to deprecate some version of Angular
2nd part of this will go in in another PR, which is to update the angular major version based on support in an automated way
=> DTSPO-15800:Add angular version

terraform-infra-approvals/ccd-data-store-api.json
Notes:
* Added for testing storage auto growth for postgres flexible server on ccd-data-store-api
* In relation to https://tools.hmcts.net/jira/browse/DTSPO-16954
=> Testing storage auto growth in ccd

terraform-infra-approvals/rd-caseworker-ref-api.json
Notes:
* Pointing rd-caseworker-ref-api to test branch in terraform-module-postgresql-flexible.
* Will be using this branch to test this change https://github.com/hmcts/terraform-module-postgresql-flexible/pull/58
*
=> Pointing app to postgres flexible test branch

.github/workflows/angular-update.yml, scripts/angular-version.sh
Pushing to master is blocked due to branch protection, second best is a PR created via automation instead, this change adds that functionality.
Removes previous code which was attempting to push to master
=> DTSPO-15800: Change to raise a PR instead

terraform-infra-approvals/camunda-bpm.json
Notes:
* Allowing module call to temp postgresql branch for camunda-bpm
* Related to work on https://tools.hmcts.net/jira/browse/DTSPO-17274
=> Allow temp module call for camunda-bpm

deprecation-config.yml
Related to DTSPO-17525, on upgrading eg. chart-java, teams that also use chart-ccd have errors coming from charts within chart-ccd.
Move java/node/base dates out to enable us to investigate ccd-chart issue and give teams time to get changes in if necessary.
=> Move time to enable us to fix ccd chart issues

terraform-infra-approvals/ccd-elastic-search.json
SSH isn't working because the module is private. Switching to https to unblock temporarily whilst I figure out the issue in the backgroun
=> Temp add https version for ccd-elastic-search

terraform-infra-approvals/ccd-elastic-search.json
Reverts hmcts/cnp-jenkins-config#1067
Didn't solve it. Issue was more related to the fact jenkins is not set up to use modules that are private in github
=> Revert "Temp add https version for ccd-elastic-search"

deprecation-config.yml
Updated most dependencies in chart-ccd and created a new release, but there was one error remaining because that dependency had no new version and ccd will need to look into getting that up to date. Testing a new fix from chart perspective today but need to give teams more time to take this into account.
=> Extend for ccd-chart issues

environment-approvals.yml
Notes:
* Adding new docmosis-infrastructure repo to allow list for prod environment
* https://github.com/hmcts/docmosis-infrastructure
=> Add docmosis-infrastructure repo to allow list for prod

team-config.yml
Notes:
* Changes docmosis channel id to #platops-build-notices channel to receive alerts
* Previously was #platops-help channel but would not have permissions to write here
=> Update channel id docmosis

terraform-infra-approvals/ccd-elastic-search.json
Notes:
*whitelist branch to test auto shutdown tag on ccd-elastic-search  to fix this issue https://build.hmcts.net/blue/organizations/jenkins/HMCTS_a_to_c%2Fccd-elastic-search/detail/PR-103/3/pipeline/
*
*
=> whitelist branch to test auto shutdown tag on ccd-elastic-search

terraform-infra-approvals/global.json
Also removes approval for `cnp-module-storage-account` branch `azurermv2` as a search found no one uses it any more.
=> Globally approve 4.x branch for storage account

terraform-infra-approvals/global.json
Needed to add location for app insights alert (but any version more than 6 months old doesn't have it so put into a separate branch)
Notes:
*
*
*
=> app insights 4.x branch

terraform-infra-approvals/lau-case-backend.json
Adding random_password to whitelist for lau-case-backend repo
PR Created in lau-case-backend for generating  random_password for encryption key
https://github.com/hmcts/lau-case-backend/pull/756
=> LAU-948 adding random_password to whitelist

terraform-infra-approvals/sscs-shared-infrastructure.json
Copied from https://github.com/hmcts/cnp-jenkins-config/blob/master/terraform-infra-approvals/sscs-hearings-api.json#L3 as the repo is getting deprecated. 
https://tools.hmcts.net/jira/browse/SSCSSI-416
=> Moving Hearings Infra to shared infra repo

terraform-infra-approvals/cnp-plum-recipes-service.json
This is required to test the new 4.x branch created for the repo `cnp-module-redis`, as a part of solution implemented for DTSPO-22371
=> whitelist the 4.x branch of cnp-module-redis

team-config.yml
Adding a new team config block for Recipes services to allow builds via cnp Jenkins
=> Adding recipes team config to allow Jenkins builds

terraform-infra-approvals/sscs-shared-infrastructure.json
Whitelist cnp-module-storage-account?ref=fix/private-endpoint-provider-4.x for SSCS. Needed to update azurerm to 4.x
=> SSCSCI-1542 Whitelist private-endpoint-provider-4.x branch for SSCS

terraform-infra-approvals/global.json
Getting the following error when I try to use cnp-module-metric-alert.
Before I changed from the https version, I was getting this error:
@Tyler-35
=> Add https version of cnp-module-metric-alert as it's erroring on pipeline

terraform-infra-approvals/civil-service.json
Notes:
* Allowing two branches of `terraform-module-servicebus-subscription` module
* One is for testing a change and the other is the branch they will move to once change tested and confirmed working
=> Adding allowed module branches for civil-service

terraform-infra-approvals/cnp-plum-recipes-service.json
Resolves [1149](https://github.com/hmcts/cnp-plum-recipes-service/pull/1149)
Notes:
* Adding postgres module testing branch to cnp-plum-recipes-service whitelist to allow PR checks to pass
=> DTSPO-25133: Adding module testing branch to plum-recipes whitelist

terraform-infra-approvals/ccpay-payment-api-gateway.json
Resolves https://tools.hmcts.net/jira/browse/PAY-7820
Notes:
* Payment Failure requests from external supplier Liberata are not coming through. 
* Need the CFT API Management logging on this component to diagnose issues.
=> PAY-7820: Enable CFT API Mgmt logging for ccpay-payment-app

terraform-infra-approvals/global.json
Module branch is attempting to resolve issue with namespace_name not being an expected value in the data resource for service bus subscriptions
=> DTSPO-26253 - Allow testing of module branch
